language: objective-c
osx_image: xcode9.4
branches:
  only:
    - develop
before_install:
  - echo -e "machine github.com\n  login $GITHUB_ACCESS_TOKEN" >> ~/.netrc
install:
  - gem update fastlane
  - gem install xcodeproj
before_script:
  - pod install
  - travis_wait carthage bootstrap --platform iOS
script:
  - fastlane test
  - if [ "$TRAVIS_EVENT_TYPE" = "push" ]; then fastlane beta; fi
